version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: genie_rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=genie
      - RABBITMQ_DEFAULT_PASS=genie123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - genie_network

volumes:
  rabbitmq_data:
    name: genie_rabbitmq_data

networks:
  genie_network:
    name: genie_network
    driver: bridge 