"""Initial migration

Revision ID: 2c96784b3c2d
Revises: 
Create Date: 2025-04-10 20:09:23.923795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c96784b3c2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invitations_id', table_name='invitations')
    op.drop_index('ix_invitations_invite_code', table_name='invitations')
    op.drop_index('ix_invitations_invitee_email', table_name='invitations')
    op.drop_index('ix_invitations_invitee_phone', table_name='invitations')
    op.drop_table('invitations')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_phone_number', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('invited_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name='users_invited_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_phone_number', 'users', ['phone_number'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('invitations',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('inviter_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('invitee_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('invitee_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('invite_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('accepted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('invitee_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], name='invitations_invitee_id_fkey'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], name='invitations_inviter_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invitations_pkey')
    )
    op.create_index('ix_invitations_invitee_phone', 'invitations', ['invitee_phone'], unique=False)
    op.create_index('ix_invitations_invitee_email', 'invitations', ['invitee_email'], unique=False)
    op.create_index('ix_invitations_invite_code', 'invitations', ['invite_code'], unique=True)
    op.create_index('ix_invitations_id', 'invitations', ['id'], unique=False)
    # ### end Alembic commands ### 