"""added is seen

Revision ID: 4038d2c387ec
Revises: a072d5284147
Create Date: 2025-05-10 11:19:50.538489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4038d2c387ec'
down_revision: Union[str, None] = 'a072d5284147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('private_chat_messages')
    op.add_column('shares', sa.Column('is_Seen', sa.Boolean(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('archetypes_gin_idx', table_name='users', postgresql_using='gin')
    op.drop_index('keywords_gin_idx', table_name='users', postgresql_using='gin')
    op.drop_column('users', 'archetypes_array_backup')
    op.drop_column('users', 'keywords_array_backup')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('keywords_array_backup', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('archetypes_array_backup', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.create_index('keywords_gin_idx', 'users', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('archetypes_gin_idx', 'users', ['archetypes'], unique=False, postgresql_using='gin')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('shares', 'is_Seen')
    op.create_table('private_chat_messages',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('SENT', 'DELIVERED', 'READ', name='messagestatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name='private_chat_messages_receiver_id_fkey'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='private_chat_messages_sender_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='private_chat_messages_pkey')
    )
    # ### end Alembic commands ###
