"""increase length of imageURL field on the recommendations model

Revision ID: e20049aa84ff
Revises: ac08f5eb8b7b
Create Date: 2025-06-06 10:34:45.178113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e20049aa84ff'
down_revision: Union[str, None] = 'ac08f5eb8b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recommendations', 'image_url', type_=sa.String(length=2048), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recommendations', 'image_url', type_=sa.String(length=255), nullable=True)
    # ### end Alembic commands ###
