"""Add keywords and archetypes to user model

Revision ID: e98db86d0001
Revises: c778d31e12d8
Create Date: 2025-04-10 20:51:00.538183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98db86d0001'
down_revision = 'c778d31e12d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('archetypes', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'keywords')
    op.drop_column('users', 'archetypes')
    # ### end Alembic commands ### 