"""Fix user_id type on UserRecommendations and add missing relationship on User model

Revision ID: eef763a7148e
Revises: 450e268c701c
Create Date: 2025-05-21 18:26:57.114314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef763a7148e'
down_revision: Union[str, None] = '450e268c701c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_recommendations', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key('fk_user_recommendations_user_id', 'user_recommendations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_recommendations_user_id', 'user_recommendations', type_='foreignkey')
    op.alter_column('user_recommendations', 'user_id',
               existing_type=sa.String(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###
